#!/usr/bin/env sh
## YABAI STUFF

# bsp or float (default: bsp)
# yabai -m config layout bsp

# Custom names for spaces

# float system preferences. Most of these just diable Yabai form resizing them.
yabai -m rule --add app="^System Preferences$" manage=off
yabai -m rule --add app="^System Settings$" manage=off
yabai -m rule --add app="^Karabiner-Elements$" manage=off
yabai -m rule --add app="^Karabiner-EventViewer$" manage=off
yabai -m rule --add app="^Finder$" manage=off
yabai -m rule --add app="^Keka$" manage=off
yabai -m rule --add app="^Alfred Preferences$" manage=off
yabai -m rule --add app="^Disk Utility$" manage=off
yabai -m rule --add app="^System Information$" manage=off
yabai -m rule --add app="^Activity Monitor$" manage=off
yabai -m rule --add app="^Path Finder$" manage=off
yabai -m rule --add app="^TeamViewer$" manage=off
yabai -m rule --add app="Fantastical" manage=off
yabai -m rule --add app="^Spotify$" manage=off
yabai -m rule --add app="^Flux$" manage=off
yabai -m rule --add app="^Time Out$" manage=off
yabai -m rule --add app="^perl_client_app$" manage=off
yabai -m rule --add app="^console$" manage=off
yabai -m rule --add app="^Harvest$" manage=off
yabai -m rule --add app="^CiscoSparkHelper$" manage=off
yabai -m rule --add app="^Logi Options$" manage=off
yabai -m rule --add app="^Cisco Webex Start$" manage=off
yabai -m rule --add app="^Private Internet Access$" manage=off
yabai -m rule --add app="^Deezer" manage=off
yabai -m rule --add app="^Safari" manage=off
yabai -m rule --add app="Cisco" manage=off
yabai -m rule --add app="Microsoft Remote Desktop" manage=off
yabai -m rule --add app="1Password" manage=off
yabai -m rule --add app="VMware" manage=off
yabai -m rule --add app="^Appstore" manage=off
yabai -m rule --add app="^ProtonVPN" manage=off
yabai -m rule --add app="^Battle.net" manage=off
yabai -m rule --add app="^Steam" manage=off
yabai -m rule --add app="^zoom.us" manage=off

# find ~/Library/Parallels/Applications\ Menus/ -maxdepth 3 -type f | awk -F'/' '{ print $NF; }' | awk '{$1=$1};1' | sort | uniq | tr "\n" "\0" | xargs -0 -I{} yabai -m rule --add app="^{}\$" title=".*" manage=on

## Some random global settings
# yabai -m config focus_follows_mouse          autoraise
# yabai -m config focus_follows_mouse          on
yabai -m config mouse_follows_focus on
## New window spawns to the right if vertical split, or bottom if horizontal split
yabai -m config window_placement second_child
yabai -m config window_opacity on
yabai -m config window_opacity_duration 0.50
yabai -m config active_window_opacity 1.0
yabai -m config normal_window_opacity 0.7


## WTIH SIP DISABLED (Limelight build into Yabai, enable it here)
# yabai -m config insert_feedback_color        0xffd75f5f

## some other settings
yabai -m config auto_balance off
yabai -m config split_ratio 0.50
# # set mouse interaction modifier key (default: fn)
yabai -m config mouse_modifier ctrl
# set modifier + right-click drag to resize window (default: resize)
yabai -m config mouse_action2 resize
# set modifier + left-click drag to resize window (default: move)
yabai -m config mouse_action1 move

## general space settings
# yabai -m config focused_border_skip_floating  1
# yabai -m config --space 3 layout             float

## Change how yabai looks
yabai -m config layout bsp
yabai -m config top_padding 0
yabai -m config bottom_padding 0
yabai -m config left_padding 0
yabai -m config right_padding 0
yabai -m config window_gap 3

# enable borders
borders active_color=0xff00ff00 inactive_color=0xff494d64 width=5.0 &

echo "yabai configuration loaded.."

#END
